# 失敗したテストを自動で再試行するように設定する

失敗したテストを自動で再実行されるようにしてみましょう。

---

## 概要 {#overview}

このチュートリアルでは、[自動再試行機能](/docs/use/test#automatic-retry)の使い方を学びます。

これを完了すると、テストが失敗した場合に自動で再試行するように設定されます。  
これによりテストが偶然失敗した場合に、 CI が失敗することを防いだり、
余分なデバグ作業を減らします。

## ステップ１：設定ファイルを開く {#step1-open-config-file}

まず、 `plugins/Scenamatica/config.yml` を開き、以下の項目を確認します：

```yaml title="plugins/Scenamatica/config.yml"

# ...
execution:
  # ...
  # シナリオの実行に失敗した場合の自動再実行についての設定を定義します。
  retry:
    # シナリオの再実行を有効にするかどうかを設定します。
    enabled: false
    # シナリオの実行を試みる最大回数を設定します。
    # この設定は `enabled` が有効な場合のみ有効です。
    maxAttempts: 3

#...
```

## ステップ２：自動再試行を構成する {#step2-configure-automatic-retry}

自動再試行を有効にするために、まずは `enabled` を `true` に設定します。

```yaml title="plugins/Scenamatica/config.yml"

# ...
execution:
  # ...
  # シナリオの実行に失敗した場合の自動再実行についての設定を定義します。
  retry:
    # シナリオの再実行を有効にするかどうかを設定します。
    # highlight-next-line
    enabled: true
    # シナリオの実行を試みる最大回数を設定します。
    # この設定は `enabled` が有効な場合のみ有効です。
    maxAttempts: 3

#...
```

また、 `maxAttempts` を適切な回数に設定します。基本的には、デフォルトのままで問題ありません。
この例では、最大試行回数を `2` に設定しています。

:::caution

一般的なプラグインの場合、何度も実行しないと成功しないといったことはありません。  
そのため、基本値の `3` が適切な値だと思われます。

:::

```yaml title="plugins/Scenamatica/config.yml"

# ...
execution:
  # ...
  # シナリオの実行に失敗した場合の自動再実行についての設定を定義します。
  retry:
    # シナリオの再実行を有効にするかどうかを設定します。
    enabled: true
    # シナリオの実行を試みる最大回数を設定します。
    # この設定は `enabled` が有効な場合のみ有効です。
    # highlight-next-line
    maxAttempts: 2

#...
```

### ステップ3．動作を確認する {#step4-check-behavior}

実際にシナリオを実行してみましょう。  
もしシナリオが失敗した場合に、自動で再試行されることを確認したら、このチュートリアルは完了です。お疲れ様でした。
