# プラグイン

command.enable.help=Scenamatica のシナリオ実行を有効/無効にします。
command.enable.invalidState=%%red%%有効/無効の値が不正です。
command.enable.current=%%aqua%%Scenamatica のシナリオ実行は現在 %%state%%%%aqua%% です。
command.enable.enable=%%green%%有効
command.enable.disable=%%red%%無効

command.scenario.help=シナリオを管理または実行します。
command.scenario.start.help=シナリオを実行します。
command.scenario.start.errors.noPlugin=指定されたプラグイン %%plugin%% が見つかりません。
command.scenario.start.errors.noScenario=指定されたシナリオ %%scenario%% が見つかりません。
command.scenario.start.success=シナリオ %%scenario%% の実行をキューに追加しました。

command.scenario.cancel.help=現在実行されているシナリオをキャンセルします。
command.scenario.cancel.running=現在 プラグイン %%plugin%% の シナリオ %%scenario%% が実行されています。
command.scenario.cancel.confirm=本当にシナリオ %%scenario%% の実行をキャンセルしますか？
command.scenario.cancel.errors.notRunning=シナリオは実行されていません。
command.scenario.cancel.errors.cancel=シナリオ %%scenario%% のキャンセルはユーザによって取り消されました。
command.scenario.cancel.success=シナリオ %%scenario%% の実行をキャンセルしました。

test.start=シナリオ %%scenario%% のテストが %%trigger%% により開始されました。
test.action.run=スケジュールされたアクション %%action%% を実行します。
test.action.run.fail=%%bold%%❌%%reset%% スケジュールされたアクション %%action%% の実行は %%cause%% により失敗しました。
test.action.run.success=%%bold%%✔%%reset%% スケジュールされたアクション %%action%% の実行に成功しました。
test.action.watch=予期されたアクション %%action%% が実行されるか監視します。
test.action.watch.done=%%bold%%✔%%reset%% 監視されたアクション %%action%% がプラグインにより実行されました。
test.action.jumped=%%bold%%⚠%%reset%% シナリオ %%scenarioName%% のアクション %%actionName%% が期待されるアクションよりも先に実行されました。

test.result=テスト結果: %%result%% %%white%%- %%message%%
test.result.passed=%%green%%✔ 成功
test.result.failed=%%red%%❌ 失敗
test.result.cancelled=%%yellow%%⚠ キャンセル
test.result.unknown=%%gray%%❓ 不明

test.result.message.passed=%%green%%テストは正常に完了しました。
test.result.message.context_preparation_failed=%%red%%テストの実行に必要なコンテキストの準備に失敗しました。
test.result.message.action_execution_failed=%%red%%スケジュールされたアクションの実行に失敗しました。
test.result.message.action_expectation_jumped=%%red%%期待されたアクションよりも先に他のアクションが実行されました。
test.result.message.scenario_timed_out=%%red%%シナリオが指定された時間内に実行されませんでした。
test.result.message.illegal_condition=%%red%%コンディションチェック時に不正な値が検出されました。
test.result.message.internal_error=%%red%%予期しない内部エラーが発生しました。
test.result.message.cancelled=%%yellow%%テストはキャンセルされました。
test.result.message.skipped=%%gray%%テストはスキップされました。

test.result.detail=詳細情報：
test.result.detail.id=-   テストID： %%id%%
test.result.detail.state=-   テスト状態： %%state%%
test.result.detail.elapsed=-   開始時刻： %%startedAt%%、終了時刻： %%finishedAt%%、経過時間： %%elapsed%%
test.result.detail.failed=-   失敗したアクション： %%action%%
